### ISSUE TITLE
cant add the audio file from iphone

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#39]
## Bug refactor
1. the file was recorded via iPhone's native recorded app
2. the audio file was moved to one of the device's folder
3. I tried to add that file >> but I could not pick it - it looks disable

## Screenshot for step3
![image](https://user-images.githubusercontent.com/20342245/224035302-981a09fd-f8cb-4df5-bbb4-5fd14ec7627a.png)

**Comment by itzikd1** [comment]
i belive it's fixed if not tell me what audio type it is, currently supported:
    'audio/aac',
    'audio/mpeg',
    'audio/ogg',
    'audio/opus',
    'audio/3gpp',
    'audio/webm',
    'audio/wav',
    'audio/m4a',
    'audio/mpeg',
    'audio/x-wav',
    'audio/x-aiff',
    'audio/x-m4a',
    'audio/x-caf',
    'audio/amr',
    'audio/flac',
    'audio/vnd.wave',

**Comment by amityizr** [comment]
amazing
