### ISSUE TITLE
click on "done" did card >>> show video page

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#41]
click the "כניסה למשימה" when card DID is with status `DONE` >>> goes to show did video page

## link
https://www.figma.com/file/RcQHcIwFK1tvYS13OYBdh2/Code-for-Israel--Hameorer-Project?node-id=1116-4325&t=8iUTdL5QQMoRBrod-4

## Screenshot
<img width="292" alt="image" src="https://user-images.githubusercontent.com/20342245/224087618-c1133740-5f30-40a9-9fc9-92369b5222a7.png">

**Comment by itzikd1** [comment]
done - currently showing a specific link of DID, once i know where its saved in the api data, il replace it.

**Comment by amityizr** [comment]
works great!!
