### ISSUE TITLE
show done did video page

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#42]
## UI
- get & show figure data
- get & show the story's video
- download button for downloading the video to the user's device

## link
https://www.figma.com/file/RcQHcIwFK1tvYS13OYBdh2/Code-for-Israel--Hameorer-Project?node-id=1076-4568&t=8iUTdL5QQMoRBrod-4

## Screenshot
![image](https://user-images.githubusercontent.com/20342245/224087046-021e7034-5518-4793-98c9-6d367baa8b67.png)

**Comment by itzikd1** [comment]
currently works without download

**Comment by amityizr** [comment]
this is good to go
