### ISSUE TITLE
[pick did figure] on step1 no padding to the footer-navbar

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#43]
## Bug refactor

1. sign in
2. click "+"
3. click "animated figure"
4. UI bug: on step1 the bottom-navbar is to close to the bottom (by-the-way: on step2 its good)

## Screenshot
![image](https://user-images.githubusercontent.com/20342245/224143955-1beca625-d0e0-43cb-9215-4f940bb98f7c.png)

**Comment by itzikd1** [comment]
i think i fixed, if not please take 2 pictures since i didnt understand

**Comment by amityizr** [comment]
this is great
