### ISSUE TITLE
[did] on step1 as student >> can move to next step without picking a figure

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#49]
## Bug refactor
1. sign in as a STUDENT user
2. click "+" >>> did mission
3. do nothing on step 1 && click NEXT
4. BUG: move to step2
5. SHOULD: should not move to step2 without picking a figure & button should be disabled until picking a figure

![image](https://user-images.githubusercontent.com/20342245/224326342-fe009dda-e78f-4a4b-8e15-d8ed29314cef.png)

**Comment by itzikd1** [comment]
removed next button

**Comment by amityizr** [comment]
works
