### ISSUE TITLE
[did] add DOWNLOAD button on MOVIE DONE PAGE for student

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#51]
## User Story
as a student, who want to download a ready DID-movie, so he clicks a button and download the movie-file to his device

## Link
https://www.figma.com/file/RcQHcIwFK1tvYS13OYBdh2/Code-for-Israel--Hameorer-Project?node-id=1076%3A4568&t=OJlwy4Qs3FhInog9-4

## Screenshot
<img width="246" alt="Screenshot 2023-03-10 at 15 25 45" src="https://user-images.githubusercontent.com/20342245/224327843-38af0692-68cf-497e-9160-a826f4fa1c20.png">

**Comment by itzikd1** [comment]
done

**Comment by amityizr** [comment]
looks good
