### ISSUE TITLE
[did-iphone] no border on bg-color on checkbox and radio 

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#52]
on the feedback page for MADRICH >> I can't see the place that MADRICH should click DONE

![image](https://user-images.githubusercontent.com/20342245/224334495-59c0400d-3168-4487-a059-3e0ae640cac3.png)

![image](https://user-images.githubusercontent.com/20342245/224334447-09bf5559-9f74-4ed4-8f75-350d6b8f0602.png)

**Comment by itzikd1** [comment]
fixed

**Comment by amityizr** [comment]
works
