### ISSUE TITLE
[did] remove "download" button" and add 4 icons under the movie

### ISSUE THREAD

**Issue by amityizr** [Code-For-Israel/Hameorer-client#67]
on `done` did page 
* remove the "download" button
* add small topic: "שתפו"
* add 4 icons for social network (just images - not link - not actionable - just images)

### images for the social network:
![social](https://user-images.githubusercontent.com/20342245/224557271-8f329f7c-261c-42a4-b5e5-953177942f0f.png)

## Screenshot
![image](https://user-images.githubusercontent.com/20342245/224556807-701bdb95-211a-4e7d-8241-e64de883397d.png)

**Comment by itzikd1** [comment]
תוקן וגם השיתוף עובד (אבל חסמתי)

**Comment by amityizr** [comment]
great :)
